---
- name: Install WP-CLI
  get_url:
    url: "{{ wp_cli_phar_url }}"
    dest: "{{ wp_cli_bin_path }}"
    mode: 0755

- name: Get WP-CLI tab completions
  command: curl -4Ls {{ wp_cli_completion_url }} -o /tmp/{{ wp_cli_bash_filename }}
  args:
    creates: /tmp/wp_cli_bash_filename
    warn: false

- name: Install WP-CLI tab completions
  command: rsync --checksum --chmod=0644 --info=name /tmp/{{ wp_cli_bash_filename }} {{ wp_cli_completion_dest }}
  args:
    warn: false
  register: wp_cli_completion
  changed_when: wp_cli_completion.stdout == "{{ wp_cli_bash_filename }}"
